# Generated by Django 5.2.17 on 2026-08-19 18:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=32)),
                ('provider_event_id', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', '-created_at'], name='core_webhoo_provide_ec487b_idx'), models.Index(condition=models.Q(('processed_at__isnull', True)), fields=['provider', 'created_at'], name='webhook_event_unprocessed')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_event_id'), name='webhook_event_unique_per_provider')],
            },
        ),
    ]
