# Generated by Django 5.2.17 on 2026-08-19 18:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_review_events_record_submissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_object_key', models.CharField(help_text="Key in our bucket. Server-generated and random — never a user's filename.", max_length=512)),
                ('source_bytes', models.BigIntegerField()),
                ('source_checksum', models.CharField(blank=True, max_length=128)),
                ('provider', models.CharField(max_length=32)),
                ('provider_asset_id', models.CharField(blank=True, max_length=128)),
                ('provider_playback_id', models.CharField(blank=True, max_length=128)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting upload'), ('UPLOADED', 'Uploaded, not yet processed'), ('TRANSCODING', 'Being processed by the provider'), ('READY', 'Playable'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('lesson', models.OneToOneField(help_text='One asset per lesson. Two would be two answers to what plays here.', on_delete=django.db.models.deletion.CASCADE, related_name='media_asset', to='catalog.lesson')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='media_asset_by_status'), models.Index(fields=['provider', 'provider_asset_id'], name='media_asset_provide_7d1355_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('provider_asset_id__contains', '://'), _negated=True), models.Q(('provider_playback_id__contains', '://'), _negated=True)), name='provider_ids_are_not_urls'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'READY'), _negated=True), models.Q(models.Q(('provider_asset_id', ''), _negated=True), models.Q(('provider_playback_id', ''), _negated=True)), _connector='OR'), name='ready_assets_are_playable'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'FAILED'), _negated=True), models.Q(('error_message', ''), _negated=True), _connector='OR'), name='failed_assets_explain_why'), models.CheckConstraint(condition=models.Q(('source_bytes__gt', 0)), name='source_has_bytes')],
            },
        ),
    ]
