"""The storage adapter, against a real S3 API.

Real code against MinIO rather than a fake (ADR-012 §1). A fake would have
been worse than nothing here: presigned uploads are exactly the thing that
goes wrong, and a fake accepts whatever we send it. These tests upload bytes
over HTTP to a signed URL and then ask the store what it received.

`urllib` rather than `requests`, because the standard library can already do a
PUT and this is not worth a dependency.
"""

from __future__ import annotations

import urllib.error
import urllib.request
import uuid

import pytest

from apps.media_assets.providers.storage import (
    MAGIC_PREFIX_BYTES,
    UnsupportedContentType,
    build_object_key,
    looks_like,
    object_storage,
)

# An ISO-BMFF header: four size bytes, then "ftyp". Enough to satisfy the
# signature check without shipping a real video into the repository.
MP4_BYTES = b"\x00\x00\x00\x20ftypisom" + b"\x00" * 64
WEBM_BYTES = b"\x1a\x45\xdf\xa3" + b"\x00" * 64
SHELL_SCRIPT = b"#!/bin/sh\nrm -rf /\n" + b"\x00" * 64


def _put(upload, body: bytes) -> int:
    """Upload to a signed URL exactly as a browser would.

    S310 is suppressed rather than worked around: the rule warns about opening
    an attacker-controlled URL, and this one was generated by our own adapter
    two lines earlier. Sending real bytes over HTTP is the whole reason these
    tests exist — a client that could not do it would be testing the fake this
    milestone deliberately avoided.
    """
    request = urllib.request.Request(  # noqa: S310
        upload.url, data=body, method=upload.method, headers=upload.headers
    )
    with urllib.request.urlopen(request, timeout=30) as response:  # noqa: S310
        return response.status


@pytest.fixture(scope="module")
def storage():
    """The real client, with a bucket that exists.

    Skips rather than fails when MinIO is not running, so `pytest` on a
    machine with no compose stack still completes — but CI runs MinIO as a
    service, so a broken adapter cannot merge.
    """
    store = object_storage()
    try:
        store.ensure_bucket()
    except Exception as exc:
        pytest.skip(f"object storage unavailable: {exc}")
    return store


@pytest.fixture
def key():
    return build_object_key(lesson_id=uuid.uuid4(), content_type="video/mp4")


class TestObjectKeys:
    """§7: randomised keys, never a user-supplied filename."""

    def test_two_keys_for_the_same_lesson_differ(self) -> None:
        """A predictable key lets one upload overwrite another."""
        lesson_id = uuid.uuid4()

        first = build_object_key(lesson_id=lesson_id, content_type="video/mp4")
        second = build_object_key(lesson_id=lesson_id, content_type="video/mp4")

        assert first != second

    def test_the_key_carries_no_user_input(self) -> None:
        """Nothing a client sends reaches the key. A filename from the browser
        is a path-traversal string and an overwrite of somebody else's object,
        and neither exists if the name is generated here."""
        key = build_object_key(lesson_id=uuid.uuid4(), content_type="video/mp4")

        assert ".." not in key
        assert key.startswith("masters/")
        assert key.endswith(".mp4")

    def test_an_unsupported_type_has_no_key(self) -> None:
        with pytest.raises(UnsupportedContentType):
            build_object_key(lesson_id=uuid.uuid4(), content_type="application/x-php")


class TestMagicBytes:
    """§7: check the bytes, not the extension."""

    def test_an_mp4_header_is_recognised(self) -> None:
        assert looks_like(prefix=MP4_BYTES[:MAGIC_PREFIX_BYTES], content_type="video/mp4")

    def test_a_webm_header_is_recognised(self) -> None:
        assert looks_like(prefix=WEBM_BYTES[:MAGIC_PREFIX_BYTES], content_type="video/webm")

    def test_a_shell_script_named_mp4_is_refused(self) -> None:
        """The whole point. An extension is whatever the uploader typed."""
        assert not looks_like(prefix=SHELL_SCRIPT[:MAGIC_PREFIX_BYTES], content_type="video/mp4")

    def test_an_mp4_declared_as_webm_is_refused(self) -> None:
        """Genuine media of the wrong type is still the wrong type — it would
        reach the transcoder as a job that cannot succeed."""
        assert not looks_like(prefix=MP4_BYTES[:MAGIC_PREFIX_BYTES], content_type="video/webm")

    def test_an_unknown_type_matches_nothing(self) -> None:
        assert not looks_like(prefix=MP4_BYTES, content_type="application/x-php")


class TestPresignedUpload:
    def test_a_signed_url_accepts_the_bytes_it_authorised(self, storage, key) -> None:
        upload = storage.presigned_upload(object_key=key, content_type="video/mp4")

        assert _put(upload, MP4_BYTES) in (200, 204)

        stored = storage.head(object_key=key)
        assert stored is not None
        assert stored.size_bytes == len(MP4_BYTES)

    def test_the_store_refuses_a_different_content_type(self, storage, key) -> None:
        """The content type is part of the signature, so this is refused by the
        *store* — not by us being polite about what we accept. That is abuse
        case 2, and it is the reason this adapter is real rather than fake."""
        upload = storage.presigned_upload(object_key=key, content_type="video/mp4")

        with pytest.raises(urllib.error.HTTPError) as raised:
            _put(
                type(upload)(
                    url=upload.url,
                    method=upload.method,
                    headers={"Content-Type": "application/x-php"},
                    object_key=upload.object_key,
                    expires_at=upload.expires_at,
                ),
                SHELL_SCRIPT,
            )

        assert raised.value.code == 403
        assert storage.head(object_key=key) is None

    def test_the_url_authorises_one_key_only(self, storage, key) -> None:
        """A URL that could write anywhere in the bucket would let one
        instructor overwrite another's master."""
        upload = storage.presigned_upload(object_key=key, content_type="video/mp4")
        elsewhere = upload.url.replace(key, "masters/somebody-else/stolen.mp4")

        with pytest.raises(urllib.error.HTTPError) as raised:
            urllib.request.urlopen(  # noqa: S310 — our own URL, retargeted on purpose
                urllib.request.Request(  # noqa: S310
                    elsewhere, data=MP4_BYTES, method="PUT", headers=upload.headers
                ),
                timeout=30,
            )

        assert raised.value.code == 403

    def test_an_unsupported_type_is_never_signed(self, storage, key) -> None:
        with pytest.raises(UnsupportedContentType):
            storage.presigned_upload(object_key=key, content_type="application/x-php")


class TestInspectingWhatLanded:
    def test_head_reports_nothing_for_an_object_never_uploaded(self, storage, key) -> None:
        """None rather than an exception: "the upload never happened" is an
        expected outcome the caller handles, not an error."""
        assert storage.head(object_key=key) is None

    def test_head_reports_the_real_size(self, storage, key) -> None:
        """The declared size is a claim; this is the fact. It is what the size
        limit is enforced against, because a presigned PUT cannot cap it."""
        upload = storage.presigned_upload(object_key=key, content_type="video/mp4")
        _put(upload, MP4_BYTES)

        assert storage.head(object_key=key).size_bytes == len(MP4_BYTES)

    def test_read_prefix_returns_only_the_prefix(self, storage, key) -> None:
        """A range request, not a download. Invariant 6 forbids pulling the
        object through Django, and this is how the type check stays cheap on a
        two-gigabyte file."""
        upload = storage.presigned_upload(object_key=key, content_type="video/mp4")
        _put(upload, MP4_BYTES)

        prefix = storage.read_prefix(object_key=key)

        assert len(prefix) == MAGIC_PREFIX_BYTES
        assert looks_like(prefix=prefix, content_type="video/mp4")

    def test_a_disguised_upload_is_caught_after_the_fact(self, storage, key) -> None:
        """The end-to-end version of abuse case 5. The store cannot know a
        file is not what it claims — the signature only fixes the declared
        type — so the bytes are checked once they are there."""
        upload = storage.presigned_upload(object_key=key, content_type="video/mp4")
        _put(upload, SHELL_SCRIPT)

        prefix = storage.read_prefix(object_key=key)

        assert not looks_like(prefix=prefix, content_type="video/mp4")

    def test_deleting_removes_it(self, storage, key) -> None:
        """Used to clean up an upload that failed verification, so the bucket
        does not accumulate objects nothing references."""
        upload = storage.presigned_upload(object_key=key, content_type="video/mp4")
        _put(upload, MP4_BYTES)

        storage.delete(object_key=key)

        assert storage.head(object_key=key) is None
