/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in
         * @description Establish a session.
         *
         *     `authenticate` runs through AxesStandaloneBackend first, so a locked
         *     account fails here exactly as a wrong password does — and says the same
         *     thing. Telling a caller "this account is locked" would confirm the address
         *     exists and tell them their guessing worked well enough to matter.
         *
         *     Deliberately not CSRF-exempt. Forcing a victim's browser to sign in as the
         *     attacker is a real attack: everything they do next is recorded against the
         *     wrong account.
         */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out
         * @description Destroy the session.
         *
         *     Idempotent, and permitted while unauthenticated: a client retrying after a
         *     timeout should not receive an error for succeeding twice, and refusing an
         *     anonymous caller would leak whether their session was still alive.
         */
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The signed-in user
         * @description Who am I.
         *
         *     Identity comes from the session and nothing else. There is no path
         *     parameter, no query parameter and no header that selects a user — a
         *     stronger guarantee than filtering one out, because there is nothing to
         *     filter. architecture.md section 4.4 calls fetching by a client-supplied
         *     identifier the single most common IDOR in DRF codebases; the fix here is
         *     to never accept one.
         */
        get: operations["auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/change/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change your password
         * @description Change the password of the signed-in user.
         *
         *     The only endpoint here that requires authentication, so it uses the
         *     project default rather than AllowAny.
         */
        post: operations["auth_password_change_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/reset/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a password reset
         * @description Send a reset link.
         *
         *     Always 202. §6.2 is explicit that this must never reveal whether an account
         *     exists, and a reset endpoint is the most attractive enumeration oracle in
         *     any application because it is designed to be used by people who are locked
         *     out and therefore unauthenticated.
         */
        post: operations["auth_password_reset_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/reset/confirm/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set a new password with a reset token */
        post: operations["auth_password_reset_confirm_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register an account
         * @description Create an account and send a verification email.
         *
         *     Always answers 202 with the same body. That is abuse case 1: a differing
         *     status, body, or field error would let someone test an address list against
         *     this endpoint and learn who has an account here.
         *
         *     The response is 202 rather than 201 because the meaningful part — the email
         *     — has not happened yet, and because 201 with a Location header would imply
         *     a resource the caller may now fetch.
         */
        post: operations["auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/resend-verification/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resend the verification email
         * @description Issue a fresh verification token.
         *
         *     Same uniform response for the same reason, and it covers three cases that
         *     must look identical: no such account, an account already verified, and a
         *     genuine resend.
         */
        post: operations["auth_resend_verification_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-email/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify an email address
         * @description Consume a verification token.
         *
         *     Unlike registration this one may fail visibly: the caller is holding a
         *     token and needs to know it did not work. It still says only that the token
         *     is invalid, never which of unknown, expired or already-used applies —
         *     telling them would turn a failed guess into information.
         */
        post: operations["auth_verify_email_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogue/courses/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Published courses, by slug.
         *
         *     ``AllowAny`` is explicit and deliberate: DRF is configured to deny by
         *     default, so a public endpoint is an exemption, and an exemption is a thing
         *     to test rather than assume. ``authentication_classes = ()`` goes with it —
         *     the catalogue must behave identically for a signed-in visitor and an
         *     anonymous one, and skipping session lookup is also what keeps the response
         *     cacheable at the edge (invariant 15).
         *
         *     Read-only because there is no public write anywhere in this product.
         */
        get: operations["catalogue_courses_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogue/courses/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One published course, with its curriculum
         * @description Published courses, by slug.
         *
         *     ``AllowAny`` is explicit and deliberate: DRF is configured to deny by
         *     default, so a public endpoint is an exemption, and an exemption is a thing
         *     to test rather than assume. ``authentication_classes = ()`` goes with it —
         *     the catalogue must behave identically for a signed-in visitor and an
         *     anonymous one, and skipping session lookup is also what keeps the response
         *     cacheable at the edge (invariant 15).
         *
         *     Read-only because there is no public write anywhere in this product.
         */
        get: operations["catalogue_courses_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogue/languages/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Languages on offer
         * @description Languages a visitor can actually browse.
         *
         *     Unpaginated: this list is bounded by the number of languages taught, which
         *     is a handful, and a paginated filter control is a worse control.
         */
        get: operations["catalogue_languages_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instructor/courses/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description CRUD over the courses you own.
         *
         *     There is deliberately **no publish action here at all**. An instructor's
         *     only forward move is ``submit-for-review``; the route to PUBLISHED exists
         *     solely in Django Admin, for admins (ADR-007 §2). Absence is a stronger
         *     guarantee than a permission check on an endpoint that exists.
         */
        get: operations["instructor_courses_list"];
        put?: never;
        /**
         * @description CRUD over the courses you own.
         *
         *     There is deliberately **no publish action here at all**. An instructor's
         *     only forward move is ``submit-for-review``; the route to PUBLISHED exists
         *     solely in Django Admin, for admins (ADR-007 §2). Absence is a stronger
         *     guarantee than a permission check on an endpoint that exists.
         */
        post: operations["instructor_courses_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instructor/courses/{course_pk}/lessons/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lessons of one of your courses. */
        get: operations["instructor_courses_lessons_list"];
        put?: never;
        /** @description Lessons of one of your courses. */
        post: operations["instructor_courses_lessons_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instructor/courses/{course_pk}/lessons/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lessons of one of your courses. */
        get: operations["instructor_courses_lessons_retrieve"];
        /** @description Lessons of one of your courses. */
        put: operations["instructor_courses_lessons_update"];
        post?: never;
        /** @description Lessons of one of your courses. */
        delete: operations["instructor_courses_lessons_destroy"];
        options?: never;
        head?: never;
        /** @description Lessons of one of your courses. */
        patch: operations["instructor_courses_lessons_partial_update"];
        trace?: never;
    };
    "/api/v1/instructor/courses/{course_pk}/lessons/reorder/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reorder one section's lessons
         * @description Lessons of one of your courses.
         */
        post: operations["instructor_courses_lessons_reorder_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instructor/courses/{course_pk}/review-events/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description The review history of one of your courses.
         *
         *     ``ReadOnlyModelViewSet``, and that is the security control rather than a
         *     convenience: a writable trail would let an instructor POST themselves an
         *     APPROVED event. Nothing downstream reads this table to decide access —
         *     publication runs through the state machine in ``services.py`` — so a
         *     forgery would mislead a human rather than grant anything, which is still a
         *     bug worth closing at the route.
         */
        get: operations["instructor_courses_review_events_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instructor/courses/{course_pk}/review-events/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description The review history of one of your courses.
         *
         *     ``ReadOnlyModelViewSet``, and that is the security control rather than a
         *     convenience: a writable trail would let an instructor POST themselves an
         *     APPROVED event. Nothing downstream reads this table to decide access —
         *     publication runs through the state machine in ``services.py`` — so a
         *     forgery would mislead a human rather than grant anything, which is still a
         *     bug worth closing at the route.
         */
        get: operations["instructor_courses_review_events_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instructor/courses/{course_pk}/sections/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Sections of one of your courses. */
        get: operations["instructor_courses_sections_list"];
        put?: never;
        /** @description Sections of one of your courses. */
        post: operations["instructor_courses_sections_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instructor/courses/{course_pk}/sections/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Sections of one of your courses. */
        get: operations["instructor_courses_sections_retrieve"];
        /** @description Sections of one of your courses. */
        put: operations["instructor_courses_sections_update"];
        post?: never;
        /** @description Sections of one of your courses. */
        delete: operations["instructor_courses_sections_destroy"];
        options?: never;
        head?: never;
        /** @description Sections of one of your courses. */
        patch: operations["instructor_courses_sections_partial_update"];
        trace?: never;
    };
    "/api/v1/instructor/courses/{course_pk}/sections/reorder/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reorder a course's sections
         * @description Sections of one of your courses.
         */
        post: operations["instructor_courses_sections_reorder_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instructor/courses/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description CRUD over the courses you own.
         *
         *     There is deliberately **no publish action here at all**. An instructor's
         *     only forward move is ``submit-for-review``; the route to PUBLISHED exists
         *     solely in Django Admin, for admins (ADR-007 §2). Absence is a stronger
         *     guarantee than a permission check on an endpoint that exists.
         */
        get: operations["instructor_courses_retrieve"];
        /**
         * @description CRUD over the courses you own.
         *
         *     There is deliberately **no publish action here at all**. An instructor's
         *     only forward move is ``submit-for-review``; the route to PUBLISHED exists
         *     solely in Django Admin, for admins (ADR-007 §2). Absence is a stronger
         *     guarantee than a permission check on an endpoint that exists.
         */
        put: operations["instructor_courses_update"];
        post?: never;
        /**
         * @description CRUD over the courses you own.
         *
         *     There is deliberately **no publish action here at all**. An instructor's
         *     only forward move is ``submit-for-review``; the route to PUBLISHED exists
         *     solely in Django Admin, for admins (ADR-007 §2). Absence is a stronger
         *     guarantee than a permission check on an endpoint that exists.
         */
        delete: operations["instructor_courses_destroy"];
        options?: never;
        head?: never;
        /**
         * @description CRUD over the courses you own.
         *
         *     There is deliberately **no publish action here at all**. An instructor's
         *     only forward move is ``submit-for-review``; the route to PUBLISHED exists
         *     solely in Django Admin, for admins (ADR-007 §2). Absence is a stronger
         *     guarantee than a permission check on an endpoint that exists.
         */
        patch: operations["instructor_courses_partial_update"];
        trace?: never;
    };
    "/api/v1/instructor/courses/{id}/submit-for-review/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a course for review
         * @description CRUD over the courses you own.
         *
         *     There is deliberately **no publish action here at all**. An instructor's
         *     only forward move is ``submit-for-review``; the route to PUBLISHED exists
         *     solely in Django Admin, for admins (ADR-007 §2). Absence is a stronger
         *     guarantee than a permission check on an endpoint that exists.
         */
        post: operations["instructor_courses_submit_for_review_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lessons/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read a lesson
         * @description One lesson, in full, if you may see it.
         *
         *     ``AllowAny`` is deliberate and is what makes preview lessons work for
         *     people with no account: the resolver's first branch allows a preview
         *     before it ever asks who is calling, and a blanket ``IsAuthenticated`` here
         *     would refuse them before that branch ran. Authentication is not the gate —
         *     entitlement is, and it decides for anonymous callers too.
         *
         *     ``RetrieveModelMixin`` alone, **not** ``ReadOnlyModelViewSet``. That is a
         *     security control, not a style choice, and it was written the wrong way
         *     first: ``ReadOnlyModelViewSet`` also provides ``list``, and
         *     ``has_object_permission`` is never called for a list — so ``GET
         *     /lessons/`` returned every visible lesson, bodies included, to anonymous
         *     callers. The docstring claimed "retrieve only" while the class shipped the
         *     opposite.
         *
         *     Object-level permissions cannot gate a collection. Anything that returns
         *     many lessons must either run the resolver per row or filter by a second
         *     access rule, and a second rule is the one that drifts (invariant 3). So
         *     there is no such route: curriculum comes from the public catalogue, which
         *     shows structure without content.
         */
        get: operations["lessons_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description The entitlement decision, as the frontend receives it.
         *
         *     Declared as a serializer purely so the OpenAPI schema describes the shape
         *     and invariant 16's generated types are real rather than `unknown`. Nothing
         *     constructs it — the resolver produces the values.
         */
        Access: {
            readonly allowed: boolean;
            readonly reason: string;
            readonly cta: string | null;
        };
        /**
         * @description * `SUBMITTED` - Submitted for review
         *     * `APPROVED` - Approved
         *     * `REJECTED` - Rejected
         *     * `CHANGES_REQUESTED` - Changes requested
         * @enum {string}
         */
        ActionEnum: "SUBMITTED" | "APPROVED" | "REJECTED" | "CHANGES_REQUESTED";
        /**
         * @description An instructor's view of their own course.
         *
         *     ``status``, ``published_at`` and ``instructor`` are read-only, and that is
         *     a security control rather than a convenience. A writable ``status`` would
         *     hand every instructor the publish button — the one thing
         *     ``architecture.md`` §3 promises they do not have — and a writable
         *     ``instructor`` would let them assign a course to somebody else, or claim
         *     one.
         *
         *     Ownership comes from the session in ``perform_create``, never from the
         *     request body.
         */
        Course: {
            /** Format: uuid */
            readonly id: string;
            /** @description The public URL. Unique across the catalogue, not per instructor. */
            slug: string;
            title: string;
            description?: string;
            language: number;
            level: components["schemas"]["LevelEnum"];
            /** @description Free-form tags, e.g. ['listening', 'grammar']. */
            skill_areas?: unknown;
            /**
             * @description Never writable from a request body. Changed only by services.transition.
             *
             *     * `DRAFT` - Draft
             *     * `IN_REVIEW` - In review
             *     * `PUBLISHED` - Published
             *     * `ARCHIVED` - Archived
             */
            readonly status: components["schemas"]["StatusEnum"];
            /**
             * Format: date-time
             * @description Set when an admin approves. Null means it has never been live.
             */
            readonly published_at: string | null;
            /** Format: uuid */
            readonly instructor: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description An instructor's view of their own course.
         *
         *     ``status``, ``published_at`` and ``instructor`` are read-only, and that is
         *     a security control rather than a convenience. A writable ``status`` would
         *     hand every instructor the publish button — the one thing
         *     ``architecture.md`` §3 promises they do not have — and a writable
         *     ``instructor`` would let them assign a course to somebody else, or claim
         *     one.
         *
         *     Ownership comes from the session in ``perform_create``, never from the
         *     request body.
         */
        CourseRequest: {
            /** @description The public URL. Unique across the catalogue, not per instructor. */
            slug: string;
            title: string;
            description?: string;
            language: number;
            level: components["schemas"]["LevelEnum"];
            /** @description Free-form tags, e.g. ['listening', 'grammar']. */
            skill_areas?: unknown;
        };
        /**
         * @description Read-only in both directions.
         *
         *     Every field is read-only *and* the viewset is read-only. That is
         *     deliberate belt-and-braces: if someone later swaps the base class for a
         *     ModelViewSet — the obvious "while I'm here" change — the serializer still
         *     refuses to write, and an instructor still cannot forge their own approval.
         */
        CourseReviewEvent: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly course: string;
            /** Format: uuid */
            readonly actor: string;
            /** Format: email */
            readonly actor_email: string;
            readonly action: components["schemas"]["ActionEnum"];
            readonly notes: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        /** @description For resending a verification email. */
        EmailOnlyRequest: {
            /** Format: email */
            email: string;
        };
        /**
         * @description A lesson in full, including its content.
         *
         *     The counterpart to ``PublicLessonSerializer``, which omits ``body``
         *     entirely. Two serializers rather than one with a conditional field, as
         *     ADR-008 §6 anticipated: the public one *cannot* render paid content
         *     because it has no such field, and this one is only reachable behind
         *     ``IsEntitledToLesson``. A single serializer branching on a flag would put
         *     the access decision inside the I/O layer, which invariant 2 forbids and
         *     which is one wrong branch away from serving everything.
         */
        GatedLesson: {
            /** Format: uuid */
            readonly id: string;
            readonly course_slug: string;
            /** Format: uuid */
            readonly section: string;
            readonly slug: string;
            readonly title: string;
            readonly body: string;
            readonly lesson_type: components["schemas"]["LessonTypeEnum"];
            readonly position: number;
            /** @description Watchable without a subscription. The entitlement resolver reads this in M4; it grants nothing on its own. */
            readonly is_preview: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        Language: {
            /** @description ISO 639 code, e.g. 'es'. The natural key. */
            code: string;
            /** @description English name, e.g. 'Spanish'. */
            name: string;
            /** @description e.g. 'Español'. */
            native_name: string;
        };
        /**
         * @description ``section`` is writable, and the view narrows its queryset to the course
         *     in the URL — see ``InstructorLessonViewSet.get_serializer``. That is what
         *     turns another course's section id into a 400 rather than a cross-course
         *     write, a constraint the database cannot express because both rows are
         *     individually valid.
         */
        Lesson: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly course: string;
            /** Format: uuid */
            section: string;
            slug: string;
            title: string;
            body?: string;
            lesson_type?: components["schemas"]["LessonTypeEnum"];
            position: number;
            /** @description Watchable without a subscription. The entitlement resolver reads this in M4; it grants nothing on its own. */
            is_preview?: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /** @description Shape only. Whether the ids are *yours* is decided in the service. */
        LessonReorderRequest: {
            order: string[];
            /** Format: uuid */
            section: string;
        };
        /**
         * @description ``section`` is writable, and the view narrows its queryset to the course
         *     in the URL — see ``InstructorLessonViewSet.get_serializer``. That is what
         *     turns another course's section id into a 400 rather than a cross-course
         *     write, a constraint the database cannot express because both rows are
         *     individually valid.
         */
        LessonRequest: {
            /** Format: uuid */
            section: string;
            slug: string;
            title: string;
            body?: string;
            lesson_type?: components["schemas"]["LessonTypeEnum"];
            position: number;
            /** @description Watchable without a subscription. The entitlement resolver reads this in M4; it grants nothing on its own. */
            is_preview?: boolean;
        };
        /**
         * @description * `VIDEO` - Video
         *     * `AUDIO` - Audio
         *     * `TEXT` - Text
         *     * `RESOURCE` - Resource
         * @enum {string}
         */
        LessonTypeEnum: "VIDEO" | "AUDIO" | "TEXT" | "RESOURCE";
        /**
         * @description * `A1` - A1 — Beginner
         *     * `A2` - A2 — Elementary
         *     * `B1` - B1 — Intermediate
         *     * `B2` - B2 — Upper intermediate
         *     * `C1` - C1 — Advanced
         *     * `C2` - C2 — Proficient
         * @enum {string}
         */
        LevelEnum: "A1" | "A2" | "B1" | "B2" | "C1" | "C2";
        /**
         * @description Login input.
         *
         *     No password validators here. They exist to stop weak passwords being
         *     *chosen*; applying them at login would reject a valid credential set before
         *     a stricter policy, and would leak the policy to anyone probing.
         */
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        /**
         * @description The signed-in user.
         *
         *     A field allowlist rather than a ModelSerializer with `exclude`. With
         *     `exclude`, every field added to User later is exposed by default and
         *     somebody has to remember to hide it; here the default is that new fields
         *     stay private until named.
         *
         *     `is_staff`, `is_superuser`, `groups` and `user_permissions` are therefore
         *     absent: they are internal authorisation detail, and the frontend branches
         *     on `role`.
         *
         *     `access` carries the entitlement decision, as architecture.md section 6.2
         *     requires, "so the frontend never re-derives access rules". It is the same
         *     resolver the gated endpoints use — `resolve_account_access` is the
         *     lesson-independent half of `resolve_access`, not a second copy, because two
         *     implementations of these rules disagree the day one of them changes
         *     (invariant 3).
         *
         *     A reason and a call to action, never a bare boolean: the interface has to
         *     tell "start a trial" from "your card failed", and a boolean would put that
         *     inference in the frontend.
         */
        Me: {
            /** Format: uuid */
            readonly id: string;
            /** Format: email */
            readonly email: string;
            readonly role: string;
            readonly is_email_verified: boolean;
            readonly profile: components["schemas"]["StudentProfile"];
            readonly access: components["schemas"]["Access"];
        };
        PaginatedCourseList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["Course"][];
        };
        PaginatedCourseReviewEventList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["CourseReviewEvent"][];
        };
        PaginatedLessonList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["Lesson"][];
        };
        PaginatedPublicCourseList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["PublicCourse"][];
        };
        PaginatedSectionList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["Section"][];
        };
        /**
         * @description Change a signed-in user's password.
         *
         *     The current password is required even though the caller is authenticated —
         *     a session left open on a shared machine is exactly what this stops.
         */
        PasswordChangeRequest: {
            current_password: string;
            new_password: string;
        };
        /** @description Consume a reset token and set a new password. */
        PasswordResetConfirmRequest: {
            token: string;
            new_password: string;
        };
        /**
         * @description An instructor's view of their own course.
         *
         *     ``status``, ``published_at`` and ``instructor`` are read-only, and that is
         *     a security control rather than a convenience. A writable ``status`` would
         *     hand every instructor the publish button — the one thing
         *     ``architecture.md`` §3 promises they do not have — and a writable
         *     ``instructor`` would let them assign a course to somebody else, or claim
         *     one.
         *
         *     Ownership comes from the session in ``perform_create``, never from the
         *     request body.
         */
        PatchedCourseRequest: {
            /** @description The public URL. Unique across the catalogue, not per instructor. */
            slug?: string;
            title?: string;
            description?: string;
            language?: number;
            level?: components["schemas"]["LevelEnum"];
            /** @description Free-form tags, e.g. ['listening', 'grammar']. */
            skill_areas?: unknown;
        };
        /**
         * @description ``section`` is writable, and the view narrows its queryset to the course
         *     in the URL — see ``InstructorLessonViewSet.get_serializer``. That is what
         *     turns another course's section id into a 400 rather than a cross-course
         *     write, a constraint the database cannot express because both rows are
         *     individually valid.
         */
        PatchedLessonRequest: {
            /** Format: uuid */
            section?: string;
            slug?: string;
            title?: string;
            body?: string;
            lesson_type?: components["schemas"]["LessonTypeEnum"];
            position?: number;
            /** @description Watchable without a subscription. The entitlement resolver reads this in M4; it grants nothing on its own. */
            is_preview?: boolean;
        };
        /**
         * @description ``course`` is read-only: it comes from the URL, never the body.
         *
         *     A writable ``course`` would let an instructor post a section into somebody
         *     else's course by id, which is precisely the hole the scoped queryset closes
         *     everywhere else.
         */
        PatchedSectionRequest: {
            title?: string;
            position?: number;
        };
        /**
         * @description A catalogue card.
         *
         *     ``instructor_name`` rather than the instructor's id or email: the
         *     catalogue is unauthenticated, and an email address on a public page is a
         *     spam list.
         */
        PublicCourse: {
            /** Format: uuid */
            readonly id: string;
            /** @description The public URL. Unique across the catalogue, not per instructor. */
            slug: string;
            title: string;
            description?: string;
            readonly language: components["schemas"]["Language"];
            level: components["schemas"]["LevelEnum"];
            /** @description Free-form tags, e.g. ['listening', 'grammar']. */
            skill_areas?: unknown;
            readonly instructor_name: string;
            /**
             * Format: date-time
             * @description Set when an admin approves. Null means it has never been live.
             */
            published_at?: string | null;
        };
        /**
         * @description The card plus the curriculum. Structure sells the course; content does
         *     not appear until someone is entitled to it.
         */
        PublicCourseDetail: {
            /** Format: uuid */
            readonly id: string;
            /** @description The public URL. Unique across the catalogue, not per instructor. */
            slug: string;
            title: string;
            description?: string;
            readonly language: components["schemas"]["Language"];
            level: components["schemas"]["LevelEnum"];
            /** @description Free-form tags, e.g. ['listening', 'grammar']. */
            skill_areas?: unknown;
            readonly instructor_name: string;
            /**
             * Format: date-time
             * @description Set when an admin approves. Null means it has never been live.
             */
            published_at?: string | null;
            readonly sections: components["schemas"]["PublicSection"][];
        };
        /**
         * @description A lesson as an anonymous visitor sees it: a title and a shape.
         *
         *     ``body`` is absent from ``fields``, not hidden by a condition. Entitlements
         *     arrive in M4 and there is nothing to gate with yet, so the safe form is a
         *     serializer that has no way to render paid content at all — a field that is
         *     usually hidden is one wrong branch from being visible.
         */
        PublicLesson: {
            /** Format: uuid */
            readonly id: string;
            slug: string;
            title: string;
            lesson_type?: components["schemas"]["LessonTypeEnum"];
            position: number;
            /** @description Watchable without a subscription. The entitlement resolver reads this in M4; it grants nothing on its own. */
            is_preview?: boolean;
        };
        PublicSection: {
            /** Format: uuid */
            readonly id: string;
            title: string;
            position: number;
            readonly lessons: components["schemas"]["PublicLesson"][];
        };
        /**
         * @description Registration input.
         *
         *     Two fields, and that is the security control. DRF ignores fields it does
         *     not declare, so `role`, `is_staff` and `is_superuser` in a request body go
         *     nowhere — there is no path from here to them. Abuse case 3.
         */
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        /** @description Shape only. Whether the ids are *yours* is decided in the service. */
        ReorderRequest: {
            order: string[];
        };
        /**
         * @description ``course`` is read-only: it comes from the URL, never the body.
         *
         *     A writable ``course`` would let an instructor post a section into somebody
         *     else's course by id, which is precisely the hole the scoped queryset closes
         *     everywhere else.
         */
        Section: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly course: string;
            title: string;
            position: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description ``course`` is read-only: it comes from the URL, never the body.
         *
         *     A writable ``course`` would let an instructor post a section into somebody
         *     else's course by id, which is precisely the hole the scoped queryset closes
         *     everywhere else.
         */
        SectionRequest: {
            title: string;
            position: number;
        };
        /**
         * @description * `DRAFT` - Draft
         *     * `IN_REVIEW` - In review
         *     * `PUBLISHED` - Published
         *     * `ARCHIVED` - Archived
         * @enum {string}
         */
        StatusEnum: "DRAFT" | "IN_REVIEW" | "PUBLISHED" | "ARCHIVED";
        /** @description Output only. */
        StudentProfile: {
            display_name: string;
        };
        /** @description For consuming a verification token. */
        VerifyEmailRequest: {
            token: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LoginRequest"];
                "multipart/form-data": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Signed in. A session cookie is set. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Credentials refused, or the account is locked. Deliberately one answer. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out. Idempotent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Not signed in. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_password_change_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordChangeRequest"];
                "multipart/form-data": components["schemas"]["PasswordChangeRequest"];
            };
        };
        responses: {
            /** @description Password changed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Current password wrong, or new password rejected. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_password_reset_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailOnlyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["EmailOnlyRequest"];
                "multipart/form-data": components["schemas"]["EmailOnlyRequest"];
            };
        };
        responses: {
            /** @description Accepted. Identical for unknown addresses. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_password_reset_confirm_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirmRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordResetConfirmRequest"];
                "multipart/form-data": components["schemas"]["PasswordResetConfirmRequest"];
            };
        };
        responses: {
            /** @description Password changed. All sessions are invalidated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token invalid, or the new password was rejected. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RegisterRequest"];
                "multipart/form-data": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Accepted. Identical whether or not the address was free. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Malformed input or a password that fails validation. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_resend_verification_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailOnlyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["EmailOnlyRequest"];
                "multipart/form-data": components["schemas"]["EmailOnlyRequest"];
            };
        };
        responses: {
            /** @description Accepted. Identical for unknown and verified addresses. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_verify_email_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["VerifyEmailRequest"];
                "multipart/form-data": components["schemas"]["VerifyEmailRequest"];
            };
        };
        responses: {
            /** @description Email address verified. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token unknown, expired or already used — deliberately not distinguished. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    catalogue_courses_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPublicCourseList"];
                };
            };
        };
    };
    catalogue_courses_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicCourseDetail"];
                };
            };
            /** @description No published course with that slug. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    catalogue_languages_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Language"][];
                };
            };
        };
    };
    instructor_courses_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCourseList"];
                };
            };
        };
    };
    instructor_courses_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourseRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CourseRequest"];
                "multipart/form-data": components["schemas"]["CourseRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Course"];
                };
            };
        };
    };
    instructor_courses_lessons_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path: {
                course_pk: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedLessonList"];
                };
            };
        };
    };
    instructor_courses_lessons_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_pk: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LessonRequest"];
                "multipart/form-data": components["schemas"]["LessonRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lesson"];
                };
            };
        };
    };
    instructor_courses_lessons_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_pk: string;
                /** @description A UUID string identifying this lesson. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lesson"];
                };
            };
        };
    };
    instructor_courses_lessons_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_pk: string;
                /** @description A UUID string identifying this lesson. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LessonRequest"];
                "multipart/form-data": components["schemas"]["LessonRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lesson"];
                };
            };
        };
    };
    instructor_courses_lessons_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_pk: string;
                /** @description A UUID string identifying this lesson. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    instructor_courses_lessons_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_pk: string;
                /** @description A UUID string identifying this lesson. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedLessonRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedLessonRequest"];
                "multipart/form-data": components["schemas"]["PatchedLessonRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lesson"];
                };
            };
        };
    };
    instructor_courses_lessons_reorder_create: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path: {
                course_pk: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonReorderRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LessonReorderRequest"];
                "multipart/form-data": components["schemas"]["LessonReorderRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedLessonList"];
                };
            };
            /** @description The order did not name exactly these lessons. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such course or section of yours. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    instructor_courses_review_events_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path: {
                course_pk: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCourseReviewEventList"];
                };
            };
        };
    };
    instructor_courses_review_events_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_pk: string;
                /** @description A UUID string identifying this course review event. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseReviewEvent"];
                };
            };
        };
    };
    instructor_courses_sections_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path: {
                course_pk: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSectionList"];
                };
            };
        };
    };
    instructor_courses_sections_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_pk: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SectionRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["SectionRequest"];
                "multipart/form-data": components["schemas"]["SectionRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Section"];
                };
            };
        };
    };
    instructor_courses_sections_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_pk: string;
                /** @description A UUID string identifying this section. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Section"];
                };
            };
        };
    };
    instructor_courses_sections_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_pk: string;
                /** @description A UUID string identifying this section. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SectionRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["SectionRequest"];
                "multipart/form-data": components["schemas"]["SectionRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Section"];
                };
            };
        };
    };
    instructor_courses_sections_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_pk: string;
                /** @description A UUID string identifying this section. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    instructor_courses_sections_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_pk: string;
                /** @description A UUID string identifying this section. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedSectionRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedSectionRequest"];
                "multipart/form-data": components["schemas"]["PatchedSectionRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Section"];
                };
            };
        };
    };
    instructor_courses_sections_reorder_create: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path: {
                course_pk: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ReorderRequest"];
                "multipart/form-data": components["schemas"]["ReorderRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSectionList"];
                };
            };
            /** @description The order did not name exactly these sections. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such course of yours. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    instructor_courses_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this course. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Course"];
                };
            };
        };
    };
    instructor_courses_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this course. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourseRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CourseRequest"];
                "multipart/form-data": components["schemas"]["CourseRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Course"];
                };
            };
        };
    };
    instructor_courses_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this course. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    instructor_courses_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this course. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCourseRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCourseRequest"];
                "multipart/form-data": components["schemas"]["PatchedCourseRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Course"];
                };
            };
        };
    };
    instructor_courses_submit_for_review_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this course. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Course"];
                };
            };
            /** @description No such course of yours. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not in a state that can be submitted. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    lessons_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this lesson. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatedLesson"];
                };
            };
            /** @description Entitlement denied. Problem Details with a stable `reason` and `cta` — see /problems/entitlement-denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such lesson, or not published. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
