/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in
         * @description Establish a session.
         *
         *     `authenticate` runs through AxesStandaloneBackend first, so a locked
         *     account fails here exactly as a wrong password does — and says the same
         *     thing. Telling a caller "this account is locked" would confirm the address
         *     exists and tell them their guessing worked well enough to matter.
         *
         *     Deliberately not CSRF-exempt. Forcing a victim's browser to sign in as the
         *     attacker is a real attack: everything they do next is recorded against the
         *     wrong account.
         */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out
         * @description Destroy the session.
         *
         *     Idempotent, and permitted while unauthenticated: a client retrying after a
         *     timeout should not receive an error for succeeding twice, and refusing an
         *     anonymous caller would leak whether their session was still alive.
         */
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The signed-in user
         * @description Who am I.
         *
         *     Identity comes from the session and nothing else. There is no path
         *     parameter, no query parameter and no header that selects a user — a
         *     stronger guarantee than filtering one out, because there is nothing to
         *     filter. architecture.md section 4.4 calls fetching by a client-supplied
         *     identifier the single most common IDOR in DRF codebases; the fix here is
         *     to never accept one.
         */
        get: operations["auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/change/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change your password
         * @description Change the password of the signed-in user.
         *
         *     The only endpoint here that requires authentication, so it uses the
         *     project default rather than AllowAny.
         */
        post: operations["auth_password_change_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/reset/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a password reset
         * @description Send a reset link.
         *
         *     Always 202. §6.2 is explicit that this must never reveal whether an account
         *     exists, and a reset endpoint is the most attractive enumeration oracle in
         *     any application because it is designed to be used by people who are locked
         *     out and therefore unauthenticated.
         */
        post: operations["auth_password_reset_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/reset/confirm/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set a new password with a reset token */
        post: operations["auth_password_reset_confirm_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register an account
         * @description Create an account and send a verification email.
         *
         *     Always answers 202 with the same body. That is abuse case 1: a differing
         *     status, body, or field error would let someone test an address list against
         *     this endpoint and learn who has an account here.
         *
         *     The response is 202 rather than 201 because the meaningful part — the email
         *     — has not happened yet, and because 201 with a Location header would imply
         *     a resource the caller may now fetch.
         */
        post: operations["auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/resend-verification/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resend the verification email
         * @description Issue a fresh verification token.
         *
         *     Same uniform response for the same reason, and it covers three cases that
         *     must look identical: no such account, an account already verified, and a
         *     genuine resend.
         */
        post: operations["auth_resend_verification_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-email/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify an email address
         * @description Consume a verification token.
         *
         *     Unlike registration this one may fail visibly: the caller is holding a
         *     token and needs to know it did not work. It still says only that the token
         *     is invalid, never which of unknown, expired or already-used applies —
         *     telling them would turn a failed guess into information.
         */
        post: operations["auth_verify_email_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instructor/courses/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description CRUD over the courses you own.
         *
         *     There is deliberately **no publish action here at all**. An instructor's
         *     only forward move is ``submit-for-review``; the route to PUBLISHED exists
         *     solely in Django Admin, for admins (ADR-007 §2). Absence is a stronger
         *     guarantee than a permission check on an endpoint that exists.
         */
        get: operations["instructor_courses_list"];
        put?: never;
        /**
         * @description CRUD over the courses you own.
         *
         *     There is deliberately **no publish action here at all**. An instructor's
         *     only forward move is ``submit-for-review``; the route to PUBLISHED exists
         *     solely in Django Admin, for admins (ADR-007 §2). Absence is a stronger
         *     guarantee than a permission check on an endpoint that exists.
         */
        post: operations["instructor_courses_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instructor/courses/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description CRUD over the courses you own.
         *
         *     There is deliberately **no publish action here at all**. An instructor's
         *     only forward move is ``submit-for-review``; the route to PUBLISHED exists
         *     solely in Django Admin, for admins (ADR-007 §2). Absence is a stronger
         *     guarantee than a permission check on an endpoint that exists.
         */
        get: operations["instructor_courses_retrieve"];
        /**
         * @description CRUD over the courses you own.
         *
         *     There is deliberately **no publish action here at all**. An instructor's
         *     only forward move is ``submit-for-review``; the route to PUBLISHED exists
         *     solely in Django Admin, for admins (ADR-007 §2). Absence is a stronger
         *     guarantee than a permission check on an endpoint that exists.
         */
        put: operations["instructor_courses_update"];
        post?: never;
        /**
         * @description CRUD over the courses you own.
         *
         *     There is deliberately **no publish action here at all**. An instructor's
         *     only forward move is ``submit-for-review``; the route to PUBLISHED exists
         *     solely in Django Admin, for admins (ADR-007 §2). Absence is a stronger
         *     guarantee than a permission check on an endpoint that exists.
         */
        delete: operations["instructor_courses_destroy"];
        options?: never;
        head?: never;
        /**
         * @description CRUD over the courses you own.
         *
         *     There is deliberately **no publish action here at all**. An instructor's
         *     only forward move is ``submit-for-review``; the route to PUBLISHED exists
         *     solely in Django Admin, for admins (ADR-007 §2). Absence is a stronger
         *     guarantee than a permission check on an endpoint that exists.
         */
        patch: operations["instructor_courses_partial_update"];
        trace?: never;
    };
    "/api/v1/instructor/courses/{id}/submit-for-review/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a course for review
         * @description CRUD over the courses you own.
         *
         *     There is deliberately **no publish action here at all**. An instructor's
         *     only forward move is ``submit-for-review``; the route to PUBLISHED exists
         *     solely in Django Admin, for admins (ADR-007 §2). Absence is a stronger
         *     guarantee than a permission check on an endpoint that exists.
         */
        post: operations["instructor_courses_submit_for_review_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description An instructor's view of their own course.
         *
         *     ``status``, ``published_at`` and ``instructor`` are read-only, and that is
         *     a security control rather than a convenience. A writable ``status`` would
         *     hand every instructor the publish button — the one thing
         *     ``architecture.md`` §3 promises they do not have — and a writable
         *     ``instructor`` would let them assign a course to somebody else, or claim
         *     one.
         *
         *     Ownership comes from the session in ``perform_create``, never from the
         *     request body.
         */
        Course: {
            /** Format: uuid */
            readonly id: string;
            /** @description The public URL. Unique across the catalogue, not per instructor. */
            slug: string;
            title: string;
            description?: string;
            language: number;
            level: components["schemas"]["LevelEnum"];
            /** @description Free-form tags, e.g. ['listening', 'grammar']. */
            skill_areas?: unknown;
            /**
             * @description Never writable from a request body. Changed only by services.transition.
             *
             *     * `DRAFT` - Draft
             *     * `IN_REVIEW` - In review
             *     * `PUBLISHED` - Published
             *     * `ARCHIVED` - Archived
             */
            readonly status: components["schemas"]["StatusEnum"];
            /**
             * Format: date-time
             * @description Set when an admin approves. Null means it has never been live.
             */
            readonly published_at: string | null;
            /** Format: uuid */
            readonly instructor: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description An instructor's view of their own course.
         *
         *     ``status``, ``published_at`` and ``instructor`` are read-only, and that is
         *     a security control rather than a convenience. A writable ``status`` would
         *     hand every instructor the publish button — the one thing
         *     ``architecture.md`` §3 promises they do not have — and a writable
         *     ``instructor`` would let them assign a course to somebody else, or claim
         *     one.
         *
         *     Ownership comes from the session in ``perform_create``, never from the
         *     request body.
         */
        CourseRequest: {
            /** @description The public URL. Unique across the catalogue, not per instructor. */
            slug: string;
            title: string;
            description?: string;
            language: number;
            level: components["schemas"]["LevelEnum"];
            /** @description Free-form tags, e.g. ['listening', 'grammar']. */
            skill_areas?: unknown;
        };
        /** @description For resending a verification email. */
        EmailOnlyRequest: {
            /** Format: email */
            email: string;
        };
        /**
         * @description * `A1` - A1 — Beginner
         *     * `A2` - A2 — Elementary
         *     * `B1` - B1 — Intermediate
         *     * `B2` - B2 — Upper intermediate
         *     * `C1` - C1 — Advanced
         *     * `C2` - C2 — Proficient
         * @enum {string}
         */
        LevelEnum: "A1" | "A2" | "B1" | "B2" | "C1" | "C2";
        /**
         * @description Login input.
         *
         *     No password validators here. They exist to stop weak passwords being
         *     *chosen*; applying them at login would reject a valid credential set before
         *     a stricter policy, and would leak the policy to anyone probing.
         */
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        /**
         * @description The signed-in user.
         *
         *     A field allowlist rather than a ModelSerializer with `exclude`. With
         *     `exclude`, every field added to User later is exposed by default and
         *     somebody has to remember to hide it; here the default is that new fields
         *     stay private until named.
         *
         *     `is_staff`, `is_superuser`, `groups` and `user_permissions` are therefore
         *     absent: they are internal authorisation detail, and the frontend branches
         *     on `role`.
         *
         *     No `access` object until M4 (architecture.md section 6.2). Adding an
         *     optional object later is backward compatible; shipping a fake one now would
         *     invite the frontend to depend on a shape with no logic behind it.
         */
        Me: {
            /** Format: uuid */
            readonly id: string;
            /** Format: email */
            readonly email: string;
            readonly role: string;
            readonly is_email_verified: boolean;
            readonly profile: components["schemas"]["StudentProfile"];
        };
        PaginatedCourseList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["Course"][];
        };
        /**
         * @description Change a signed-in user's password.
         *
         *     The current password is required even though the caller is authenticated —
         *     a session left open on a shared machine is exactly what this stops.
         */
        PasswordChangeRequest: {
            current_password: string;
            new_password: string;
        };
        /** @description Consume a reset token and set a new password. */
        PasswordResetConfirmRequest: {
            token: string;
            new_password: string;
        };
        /**
         * @description An instructor's view of their own course.
         *
         *     ``status``, ``published_at`` and ``instructor`` are read-only, and that is
         *     a security control rather than a convenience. A writable ``status`` would
         *     hand every instructor the publish button — the one thing
         *     ``architecture.md`` §3 promises they do not have — and a writable
         *     ``instructor`` would let them assign a course to somebody else, or claim
         *     one.
         *
         *     Ownership comes from the session in ``perform_create``, never from the
         *     request body.
         */
        PatchedCourseRequest: {
            /** @description The public URL. Unique across the catalogue, not per instructor. */
            slug?: string;
            title?: string;
            description?: string;
            language?: number;
            level?: components["schemas"]["LevelEnum"];
            /** @description Free-form tags, e.g. ['listening', 'grammar']. */
            skill_areas?: unknown;
        };
        /**
         * @description Registration input.
         *
         *     Two fields, and that is the security control. DRF ignores fields it does
         *     not declare, so `role`, `is_staff` and `is_superuser` in a request body go
         *     nowhere — there is no path from here to them. Abuse case 3.
         */
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        /**
         * @description * `DRAFT` - Draft
         *     * `IN_REVIEW` - In review
         *     * `PUBLISHED` - Published
         *     * `ARCHIVED` - Archived
         * @enum {string}
         */
        StatusEnum: "DRAFT" | "IN_REVIEW" | "PUBLISHED" | "ARCHIVED";
        /** @description Output only. */
        StudentProfile: {
            display_name: string;
        };
        /** @description For consuming a verification token. */
        VerifyEmailRequest: {
            token: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LoginRequest"];
                "multipart/form-data": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Signed in. A session cookie is set. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Credentials refused, or the account is locked. Deliberately one answer. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out. Idempotent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Not signed in. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_password_change_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordChangeRequest"];
                "multipart/form-data": components["schemas"]["PasswordChangeRequest"];
            };
        };
        responses: {
            /** @description Password changed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Current password wrong, or new password rejected. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_password_reset_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailOnlyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["EmailOnlyRequest"];
                "multipart/form-data": components["schemas"]["EmailOnlyRequest"];
            };
        };
        responses: {
            /** @description Accepted. Identical for unknown addresses. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_password_reset_confirm_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirmRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordResetConfirmRequest"];
                "multipart/form-data": components["schemas"]["PasswordResetConfirmRequest"];
            };
        };
        responses: {
            /** @description Password changed. All sessions are invalidated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token invalid, or the new password was rejected. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RegisterRequest"];
                "multipart/form-data": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Accepted. Identical whether or not the address was free. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Malformed input or a password that fails validation. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_resend_verification_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailOnlyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["EmailOnlyRequest"];
                "multipart/form-data": components["schemas"]["EmailOnlyRequest"];
            };
        };
        responses: {
            /** @description Accepted. Identical for unknown and verified addresses. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_verify_email_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["VerifyEmailRequest"];
                "multipart/form-data": components["schemas"]["VerifyEmailRequest"];
            };
        };
        responses: {
            /** @description Email address verified. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token unknown, expired or already used — deliberately not distinguished. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    instructor_courses_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCourseList"];
                };
            };
        };
    };
    instructor_courses_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourseRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CourseRequest"];
                "multipart/form-data": components["schemas"]["CourseRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Course"];
                };
            };
        };
    };
    instructor_courses_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this course. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Course"];
                };
            };
        };
    };
    instructor_courses_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this course. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourseRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CourseRequest"];
                "multipart/form-data": components["schemas"]["CourseRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Course"];
                };
            };
        };
    };
    instructor_courses_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this course. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    instructor_courses_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this course. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCourseRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCourseRequest"];
                "multipart/form-data": components["schemas"]["PatchedCourseRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Course"];
                };
            };
        };
    };
    instructor_courses_submit_for_review_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this course. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Course"];
                };
            };
            /** @description No such course of yours. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not in a state that can be submitted. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
