# Generated by Django 5.2.17 on 2026-08-18 06:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text="ISO 639 code, e.g. 'es'. The natural key.", max_length=10, unique=True)),
                ('name', models.CharField(help_text="English name, e.g. 'Spanish'.", max_length=100)),
                ('native_name', models.CharField(help_text="e.g. 'Español'.", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Withdrawn languages stay for existing courses but leave the catalogue.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(help_text='The public URL. Unique across the catalogue, not per instructor.', max_length=140, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('A1', 'A1 — Beginner'), ('A2', 'A2 — Elementary'), ('B1', 'B1 — Intermediate'), ('B2', 'B2 — Upper intermediate'), ('C1', 'C1 — Advanced'), ('C2', 'C2 — Proficient')], max_length=2)),
                ('skill_areas', models.JSONField(blank=True, default=list, help_text="Free-form tags, e.g. ['listening', 'grammar'].")),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_REVIEW', 'In review'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', help_text='Never writable from a request body. Changed only by services.transition.', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, help_text='Set when an admin approves. Null means it has never been live.', null=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='catalog.language')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'language', 'level'], name='catalog_cou_status_67bcb3_idx'), models.Index(condition=models.Q(('status', 'PUBLISHED')), fields=['-published_at'], name='course_published_recent')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', False), ('status', 'PUBLISHED')), models.Q(('status', 'PUBLISHED'), _negated=True), _connector='OR'), name='course_published_has_published_at')],
            },
        ),
    ]
