# Generated by Django 5.2.17 on 2026-08-18 07:52

import django.db.models.constraints
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_coursereviewevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('position', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='catalog.course')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=140)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('lesson_type', models.CharField(choices=[('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('TEXT', 'Text'), ('RESOURCE', 'Resource')], default='VIDEO', max_length=16)),
                ('position', models.PositiveIntegerField()),
                ('is_preview', models.BooleanField(default=False, help_text='Watchable without a subscription. The entitlement resolver reads this in M4; it grants nothing on its own.')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='catalog.course')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='catalog.section')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('course', 'position'), name='section_position_unique_per_course'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['section', 'position'], name='catalog_les_section_cc9423_idx'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('course', 'slug'), name='lesson_slug_unique_per_course'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('section', 'position'), name='lesson_position_unique_per_section'),
        ),
    ]
