# Generated by Django 5.2.17 on 2026-08-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='display_name',
            field=models.CharField(blank=True, help_text='Shown on the public catalogue. Blank shows nothing.', max_length=100),
        ),
    ]
