"""Generate the local environment files.

Two files, because two different consumers need different things:

``.env`` at the repository root
    Read by ``docker compose`` for variable substitution. CLAUDE.md section 6
    forbids committing environment variable values, which rules out writing
    POSTGRES_PASSWORD straight into docker-compose.yml, so compose references
    variables that must already exist and this creates them.

``backend/.env``
    Read by Django's *local* settings via ``environ.Env.read_env``. Without it,
    running ``manage.py`` or pytest outside a container fails at import with
    "Set the DJANGO_SECRET_KEY environment variable", because the root file is
    compose's and Django never looks at it.

Both are gitignored. Both are idempotent: an existing key is never overwritten,
so running this twice cannot rotate the database password out from under a
volume that was initialised with the old one.

Secrets are generated, never defaulted to something guessable. These are local
development credentials on services that are not reachable from outside the
machine, but the habit of writing ``postgres/postgres`` is the habit that
eventually ships.
"""

from __future__ import annotations

import secrets
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
COMPOSE_ENV = REPO_ROOT / ".env"
BACKEND_ENV = REPO_ROOT / "backend" / ".env"

# What compose needs, and how to produce it when absent.
GENERATED_KEYS = {
    "DJANGO_SECRET_KEY": lambda: secrets.token_urlsafe(50),
    "POSTGRES_PASSWORD": lambda: secrets.token_urlsafe(24),
}

DEFAULT_POSTGRES_PORT = "5432"
DEFAULT_REDIS_PORT = "6379"


def parse_env(text: str) -> dict[str, str]:
    """Read KEY=VALUE lines, ignoring comments and blanks."""
    values: dict[str, str] = {}
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, value = stripped.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def read_env_file(path: Path) -> dict[str, str]:
    return parse_env(path.read_text(encoding="utf-8")) if path.exists() else {}


def missing_keys(existing: dict[str, str]) -> list[str]:
    """Keys that are absent or present but empty."""
    return [key for key in GENERATED_KEYS if not existing.get(key)]


def build_backend_env(compose_values: dict[str, str]) -> dict[str, str]:
    """Derive Django's local environment from the compose values.

    The host ports matter here and not in the container: compose talks to
    ``postgres:5432`` over its own network, whereas a developer running pytest
    on the host reaches whichever port compose published. That is overridable
    precisely because something else on the machine may already hold the
    default — see the host-port note in docker-compose.yml.
    """
    postgres_port = compose_values.get("POSTGRES_PORT") or DEFAULT_POSTGRES_PORT
    redis_port = compose_values.get("REDIS_PORT") or DEFAULT_REDIS_PORT
    password = compose_values["POSTGRES_PASSWORD"]

    return {
        "DJANGO_SETTINGS_MODULE": "config.settings.local",
        "DJANGO_SECRET_KEY": compose_values["DJANGO_SECRET_KEY"],
        "DJANGO_ALLOWED_HOSTS": "localhost,127.0.0.1",
        "DATABASE_URL": f"postgres://app:{password}@127.0.0.1:{postgres_port}/app",
        "REDIS_URL": f"redis://127.0.0.1:{redis_port}/0",
        # Database 1, matching compose. A cache flush must not empty the queue.
        "REDIS_CACHE_URL": f"redis://127.0.0.1:{redis_port}/1",
        "EMAIL_HOST": "127.0.0.1",
        "EMAIL_PORT": "1025",
    }


def render(values: dict[str, str], purpose: str) -> str:
    lines = [
        "# Generated by scripts/bootstrap_env.py. Not tracked by git.",
        f"# {purpose}",
        "# Delete this file and re-run `make bootstrap` to regenerate it.",
        "",
    ]
    lines += [f"{key}={values[key]}" for key in sorted(values)]
    return "\n".join(lines) + "\n"


def main() -> int:
    compose_values = read_env_file(COMPOSE_ENV)

    absent = missing_keys(compose_values)
    for key in absent:
        compose_values[key] = GENERATED_KEYS[key]()

    if absent:
        COMPOSE_ENV.write_text(
            render(compose_values, "Read by docker compose for variable substitution."),
            encoding="utf-8",
        )
        print(f"Wrote {COMPOSE_ENV.name} with generated: {', '.join(sorted(absent))}")
    else:
        print(f"{COMPOSE_ENV.name} already complete.")

    # Derived, so it is only written when absent — regenerating it silently
    # would discard any local override a developer had made.
    if BACKEND_ENV.exists():
        print("backend/.env already present.")
        return 0

    BACKEND_ENV.write_text(
        render(build_backend_env(compose_values), "Read by Django's local settings."),
        encoding="utf-8",
    )
    print("Wrote backend/.env for running manage.py and pytest outside a container.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
