"""Generate the local .env that docker compose reads for variable substitution.

CLAUDE.md section 6 forbids committing environment variable values, which rules
out the usual convenience of writing POSTGRES_PASSWORD straight into
docker-compose.yml. The compose file therefore references variables that must
already exist, and this creates them with freshly generated secrets.

Idempotent by design: an existing key is never overwritten, so running it twice
cannot rotate the password out from under a running database and leave the
volume unreadable.

Values are generated, never defaulted to something guessable. These are local
development credentials and the services are not reachable from outside the
machine, but a habit of writing `postgres/postgres` is the habit that
eventually ships.
"""

from __future__ import annotations

import secrets
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ENV_FILE = REPO_ROOT / ".env"

# Every key compose requires, with the generator that produces it.
GENERATED_KEYS = {
    "DJANGO_SECRET_KEY": lambda: secrets.token_urlsafe(50),
    "POSTGRES_PASSWORD": lambda: secrets.token_urlsafe(24),
}


def parse_existing(text: str) -> dict[str, str]:
    """Read KEY=VALUE lines, ignoring comments and blanks."""
    values: dict[str, str] = {}
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, value = stripped.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def missing_keys(existing: dict[str, str]) -> list[str]:
    """Keys that are absent or present but empty."""
    return [key for key in GENERATED_KEYS if not existing.get(key)]


def render(values: dict[str, str]) -> str:
    lines = [
        "# Generated by scripts/bootstrap_env.py. Not tracked by git.",
        "# Local development only. Delete this file and re-run to rotate.",
        "",
    ]
    lines += [f"{key}={values[key]}" for key in sorted(values)]
    return "\n".join(lines) + "\n"


def main() -> int:
    existing = parse_existing(ENV_FILE.read_text(encoding="utf-8")) if ENV_FILE.exists() else {}

    absent = missing_keys(existing)
    if not absent:
        print(f"{ENV_FILE.name} already complete; nothing to do.")
        return 0

    for key in absent:
        existing[key] = GENERATED_KEYS[key]()

    ENV_FILE.write_text(render(existing), encoding="utf-8")
    print(f"Wrote {ENV_FILE.name} with generated: {', '.join(sorted(absent))}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
