# Generated by Django 5.2.17 on 2026-08-20 12:49

import django.db.models.constraints
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_review_events_record_submissions'),
        ('media_assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('TARGET', 'In the language being taught'), ('TRANSLATION', 'Translated for the learner')], default='TARGET', max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Not yet transcribed'), ('MACHINE', 'Machine output, unreviewed'), ('IN_REVIEW', 'Being reviewed'), ('APPROVED', 'Reviewed and approved'), ('FAILED', 'Transcription failed')], default='PENDING', max_length=16)),
                ('provider', models.CharField(blank=True, help_text='Which system produced this. Empty until one has.', max_length=32)),
                ('provider_job_id', models.CharField(blank=True, help_text="The provider's handle for the job. How a callback finds this row.", max_length=128, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, help_text="Provider's own score, 0 to 1. Null until it has run.", max_digits=4, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transcripts', to='catalog.language')),
                ('media_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='media_assets.mediaasset')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transcripts_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('start_ms', models.IntegerField()),
                ('end_ms', models.IntegerField()),
                ('text', models.TextField()),
                ('is_edited', models.BooleanField(default=False, help_text='A human changed this. Set on edit and never cleared.')),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='transcripts.transcript')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='transcript',
            index=models.Index(fields=['media_asset', 'language', 'status'], name='transcripts_media_a_3b51f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='transcript',
            constraint=models.UniqueConstraint(fields=('media_asset', 'language', 'kind'), name='transcript_unique_per_language_and_kind'),
        ),
        migrations.AddConstraint(
            model_name='transcript',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_job_id'), name='transcript_unique_per_provider_job'),
        ),
        migrations.AddConstraint(
            model_name='transcript',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'APPROVED'), _negated=True), models.Q(('reviewed_by__isnull', False), ('approved_at__isnull', False)), _connector='OR'), name='approved_transcript_is_signed'),
        ),
        migrations.AddConstraint(
            model_name='transcript',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__isnull', True), models.Q(('confidence__gte', 0), ('confidence__lte', 1)), _connector='OR'), name='confidence_is_a_proportion'),
        ),
        migrations.AddIndex(
            model_name='transcriptsegment',
            index=models.Index(fields=['transcript', 'position'], name='transcripts_transcr_136fb2_idx'),
        ),
        migrations.AddConstraint(
            model_name='transcriptsegment',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('transcript', 'position'), name='segment_position_unique_per_transcript'),
        ),
        migrations.AddConstraint(
            model_name='transcriptsegment',
            constraint=models.CheckConstraint(condition=models.Q(('end_ms__gt', models.F('start_ms'))), name='segment_ends_after_it_starts'),
        ),
        migrations.AddConstraint(
            model_name='transcriptsegment',
            constraint=models.CheckConstraint(condition=models.Q(('start_ms__gte', 0)), name='segment_starts_within_the_media'),
        ),
    ]
