# Generated by Django 5.2.17 on 2026-08-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
