# Generated by Django 5.2.17 on 2026-08-18 23:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('TRIALING', 'Trialing'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past due'), ('CANCELED', 'Canceled'), ('EXPIRED', 'Expired')], max_length=16)),
                ('current_period_end', models.DateTimeField()),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False, help_text='Cancellation requested; access continues until current_period_end.')),
                ('provider', models.CharField(help_text="Which system told us about this. 'fake' until M8.", max_length=32)),
                ('provider_subscription_id', models.CharField(blank=True, help_text="The provider's opaque id. Null until a real provider exists.", max_length=128, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('TRIAL_STARTED', 'Trial started'), ('ACTIVATED', 'Activated'), ('RENEWED', 'Renewed'), ('PAYMENT_FAILED', 'Payment failed'), ('CANCELLATION_REQUESTED', 'Cancellation requested'), ('CANCELED', 'Canceled'), ('EXPIRED', 'Expired')], max_length=32)),
                ('from_status', models.CharField(blank=True, max_length=16)),
                ('to_status', models.CharField(blank=True, max_length=16)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='entitlements.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessOverride',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(help_text='Why this was granted. Required — an unexplained grant is the boolean again.')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_overrides_granted', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starts_at'],
                'indexes': [models.Index(fields=['user', 'starts_at', 'ends_at'], name='entitlement_user_id_b60183_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='override_ends_after_it_starts'), models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='override_requires_a_reason')],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(condition=models.Q(('status__in', ('TRIALING', 'ACTIVE', 'PAST_DUE'))), fields=['user'], name='subscription_live_by_user'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'current_period_end'], name='entitlement_status_381cda_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('TRIALING', 'ACTIVE', 'PAST_DUE'))), fields=('user',), name='one_live_subscription_per_user'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'TRIALING'), _negated=True), ('trial_end__isnull', False), _connector='OR'), name='trialing_requires_a_trial_end'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_subscription_id'), name='subscription_unique_per_provider_id'),
        ),
        migrations.AddIndex(
            model_name='subscriptionevent',
            index=models.Index(fields=['subscription', '-created_at'], name='entitlement_subscri_b8ec02_idx'),
        ),
    ]
